#MTH 5000 – Applied Forecasting of Financial Data
##Lecture 4:
##Part 1: Exporting Data   
---
Topics

*  1. Exporting Data

#1. Exporting Data   

Now that we have obtained our data it is important to know how to export it to other files in order to conduct forecasting.

## Option 1) Save the Data to your local machine as a CSV File

In [ ]:
import yfinance as yf

In [ ]:
from google.colab import files

# Example: Download Amazon weekly data
amazon_weekly = yf.download("AMZN", start="2015-01-01", end="2025-12-30", interval="1wk")

# Save to CSV
amazon_weekly.to_csv("amazon_weekly.csv")

files.download("amazon_weekly.csv")

/tmp/ipython-input-2608/577323386.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  amazon_weekly = yf.download("AMZN", start="2015-01-01", end="2025-12-30", interval="1wk")
[*********************100%***********************]  1 of 1 completed

## To import the downloaded file

In [ ]:
from google.colab import files

uploaded = files.upload()  # Select the CSV you just downloaded
import pandas as pd

amazon_weekly = pd.read_csv("amazon_weekly.csv", index_col=0, parse_dates=True)
amazon_weekly

Saving amazon_weekly.csv to amazon_weekly (1).csv

/tmp/ipython-input-2608/321806458.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  amazon_weekly = pd.read_csv("amazon_weekly.csv", index_col=0, parse_dates=True)

,Close,High,Low,Open,Volume
Price,,,,,
Ticker,AMZN,AMZN,AMZN,AMZN,AMZN
Date,NaN,NaN,NaN,NaN,NaN
2015-01-01,14.920999526977539,15.737500190734863,14.619000434875488,15.628999710083008,234334000
2015-01-08,14.66349983215332,15.156999588012695,14.324999809265137,15.015999794006348,375546000
2015-01-15,14.862500190734863,15.300000190734863,14.262499809265137,14.699999809265137,420752000
...,...,...,...,...,...
2025-11-27,232.3800048828125,238.97000122070312,230.22000122070312,231.24000549316406,144476800
2025-12-04,231.77999877929688,233.5,225.11000061035156,232.77000427246094,178452200
2025-12-11,221.27000427246094,232.11000061035156,220.99000549316406,230.7100067138672,194508100
2025-12-18,232.3800048828125,232.9499969482422,224.41000366210938,225.7100067138672,208728800
2025-12-25,232.52999877929688,232.99000549316406,230.1999969482422,232.0399932861328,57703100

## Option 2) Save to Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Save file to Drive
amazon_weekly.to_csv("/content/drive/MyDrive/amazon_weekly.csv")

Mounted at /content/drive

In [ ]:
import pandas as pd

amazon_weekly_drive = pd.read_csv("/content/drive/MyDrive/amazon_weekly.csv", index_col=0, parse_dates=True)

amazon_weekly_drive

/tmp/ipython-input-2608/1084246327.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  amazon_weekly_drive = pd.read_csv("/content/drive/MyDrive/amazon_weekly.csv", index_col=0, parse_dates=True)

,Close,High,Low,Open,Volume
Price,,,,,
Ticker,AMZN,AMZN,AMZN,AMZN,AMZN
Date,NaN,NaN,NaN,NaN,NaN
2015-01-01,14.920999526977539,15.737500190734863,14.619000434875488,15.628999710083008,234334000
2015-01-08,14.66349983215332,15.156999588012695,14.324999809265137,15.015999794006348,375546000
2015-01-15,14.862500190734863,15.300000190734863,14.262499809265137,14.699999809265137,420752000
...,...,...,...,...,...
2025-11-27,232.3800048828125,238.97000122070312,230.22000122070312,231.24000549316406,144476800
2025-12-04,231.77999877929688,233.5,225.11000061035156,232.77000427246094,178452200
2025-12-11,221.27000427246094,232.11000061035156,220.99000549316406,230.7100067138672,194508100
2025-12-18,232.3800048828125,232.9499969482422,224.41000366210938,225.7100067138672,208728800
2025-12-25,232.52999877929688,232.99000549316406,230.1999969482422,232.0399932861328,57703100

## Option 3) Using a .py file in Google Drive

In [ ]:
from google.colab import files
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

Saving fetch_data.py to fetch_data.py
User uploaded file "fetch_data.py" with length 1110 bytes

In [ ]:
import fetch_data
from fetch_data import get_weekly_data

In [ ]:
fetch_data_df = get_weekly_data("AMZN", start="2015-01-01", end = "2025-12-30",keep_columns=["Close"])

print(fetch_data_df.head())

Price           Close       High      Low     Open      Volume
Ticker           AMZN       AMZN     AMZN     AMZN        AMZN
Date
2015-01-01  14.921000  15.737500  14.6190  15.6290   234334000
2015-01-08  14.663500  15.157000  14.3250  15.0160   375546000
2015-01-15  14.862500  15.300000  14.2625  14.7000   420752000
2015-01-22  15.195500  15.846500  15.0000  15.0000   380256000
2015-01-29  18.237499  18.391001  14.9665  15.2365  1062542000